### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by compnerd**
This set of patches enables building and passing the test suite on Windows.  Primarily, treat Windows and Linux similarly.  The platform specific behaviour here is the construction of the input paths where we now use `URL(fileURLWithPath:)` and `droppingLastPathComponent` and `addingPathComponent` to compute the location of the test input.

### CODE REVIEW

**Comment by drmohundro** [comment]
🙄 of course the failure would be related to line endings!

Here's one of the failures, but the other is similar:

```text
D:\a\SWXMLHash\SWXMLHash\Tests\SWXMLHashTests\WhiteSpaceParsingTests.swift:55: error: WhiteSpaceParsingTests.testShouldBeAbleToCorrectlyParseCDATASectionsWithWhitespace : XCTAssertEqual failed: 
("Optional("\n        \r\n  this\r\n  has\r\n  white\r\n  space\r\n        \n    ")") is not equal to 
("Optional("\n        \n  this\n  has\n  white\n  space\n        \n    ")")
```

That should be easy enough to add a platform check around them, though. I can add it to the PR later or you're welcome to if you get to it first.

Thanks for the contribution @compnerd! It looks great!

**Comment by compnerd** [comment]
I think that the nicer way to handle this is via `.gitattributes` to ensure that the files are checked out in unix line endings rather than native.  That should give us the same behaviour on all the platforms.

**Review by drmohundro — APPROVED** [review]

**Comment by drmohundro** [comment]
Good call @compnerd and thanks again!

**Comment by compnerd** [comment]
My pleasure!  One favour to ask - would it be possible to get a tagged release with that by any chance?

**Comment by drmohundro** [comment]
Absolutely, I just published `7.0.2` out.

**Pull request merged**
