### PR TITLE
Add support for Carthage builds with bitcode

### PR DESCRIPTION
**Pull request by tomassliz**
Based on https://github.com/Carthage/Carthage/issues/863.

Adds support for bitcode in Carthage builds.

### CODE REVIEW

**Comment by drmohundro** [comment]
Merged, thanks!

**Comment by drmohundro** [comment]
I just realized that I'll probably need to tag a point release so that Carthage can pull your changes down, but I'm not 100% sure. Please comment if you're still seeing issues afterwards and I'll get a new tag pushed, too.

**Comment by tomassliz** [comment]
New release tag will be great but Carthage can use specific commit without this tag. I will wait until you will be ready for the next release.

**Comment by tomassliz** [comment]
And I noticed that Quick and Nimble branch 'swift-2.0' does not exist anymore. You have this in Cartfile.private.

**Comment by drmohundro** [comment]
I just pushed `2.0.3` so the bitcode support should be up. Also updated the Quick/Nimble to latest (`xcode7.1` branch so that `tvOS` works, too). Thanks!

**Comment by tomassliz** [comment]
Amazing, thank you! :+1:

**Comment by tomassliz** [comment]
Next Carthage release solve this, so it will be nice to remove BITCODE_GENERATION_MODE when it will be released. I know - It's annoying but there is not better solution ... :disappointed:

**Pull request merged**
