### PR TITLE
Add Swift 2.0 / Xcode 7.0 support

### PR DESCRIPTION
**Pull request by drmohundro**
This pull request will remain open to track Xcode 7 and Swift 2.0 support. If you're doing work with Swift 2.0, feel free to pull the [xcode-7.0 branch](https://github.com/drmohundro/SWXMLHash/tree/xcode-7.0).

The changes were all primarily done by Xcode 7 automatically.

### CODE REVIEW

**Comment by drmohundro** [comment]
One note regarding an outstanding issue I'm running into - I've updated my `Cartfile.private` to point to the Swift 2.0 versions of Quick and Nimble, but when I run `carthage update`, the build fails. If I go into the `Carthage/Checkouts` directory and run `xcodebuild` there, it works just fine, though.

I'll keep trying to track that issue down.

**Comment by tkrajacic** [comment]
With the next seed Chris Lattner hinted support for recursive enums. This could probably be relevant for type safe XML parsing. Not sure yet, just thought I needed to deposit this info ;)

**Comment by drmohundro** [comment]
Whoa, I hadn't heard that yet - other than checking out the keynote and headlines, I haven't really had a chance to dig in on much of the news this week. That sounds *very* interesting. I'm not even sure what that would look like.

**Comment by drmohundro** [comment]
I'm no longer seeing the issue with Carthage - I updated to the latest Quick/Nimble releases as well as fixed an issue with no simulator being found for the playground.

**Comment by imran20487** [comment]
@drmohundro 
Error at places where 'joinWithSeparator' API is used. I am using xcode 7 beta 4

**Comment by drmohundro** [comment]
@imran20487 this branch is up to date with the latest Xcode 7.0 beta which is beta 6 - between beta 5 and beta 6, the `joinWithSeparator` method was added (and the prior `" ".join` was removed). Hope this helps.

**Comment by drmohundro** [comment]
Looks like Xcode 7.0 is out now... I'll hopefully get this branch merged soon.

**Comment by drmohundro** [comment]
As far as semver goes, this is a breaking change so this release will be labeled `2.0.0`, primarily because this release requires Xcode 7.0 and Swift 2.0. There *are* some minor breaking changes in the API, too, though they're only related to error handling.

## Error Handling Changes/Additions in 2.0

@leoMehlig added support for Swift 2.0's new error handling (exception handling in other languages) in #35. As part of that, the previous `.Error` case is now named `.XMLError` and the new `XMLIndexer.Error` is the `ErrorType` that is thrown when there is a problem parsing.

There is also new `byIndex` and `byKey` methods if you want to explicitly catch parsing errors. There isn't `throws` support on `subscript` methods which is why they've been added; however, you can still get the `ErrorType` response by handling the `.XMLError` case.

## Other Contributions to 2.0

@fluffyemily and @jpsim helped make changes to support Swift 2.0's new `joinWithSeparator` method (#42).

In addition, thanks to everyone for reporting issues and offering feedback!

**Pull request merged**
