### PR TITLE
Disable code coverage

### PR DESCRIPTION
**Pull request by dbmrq**
Code coverage has to be disabled for Carthage to work with Xcode 9.

Check https://github.com/Carthage/Carthage/issues/2056 and https://github.com/Carthage/Carthage/pull/2057.

### CODE REVIEW

**Comment by drmohundro** [comment]
Hey, just double checking as this is the first I've heard of this - are you aware of any means of getting code coverage gathered in addition to also supporting Carthage? I'm certainly more interested in supporting Carthage, but it does sting a little to lose out on code coverage metrics.

**Comment by dbmrq** [comment]
Well, I'm not an expert, but except for using multiple schemes I don't think there's any other option for now: https://github.com/Carthage/Carthage/pull/2057#issuecomment-314440661

I'm hoping Carthage will start using the archive action, like I suggested [here](https://github.com/Carthage/Carthage/issues/2056#issuecomment-328431267), but I don't know if it's gonna happen and even if it does it might take some time.

**Comment by drmohundro** [comment]
Merged - I guess I'll keep an eye on it in case. Give me a second and I'll push another tagged version out.

**Comment by dbmrq** [comment]
Thanks! Hopefully there'll be a better way soon.

**Comment by drmohundro** [comment]
👍 `4.2.1` is now published. Thanks!

**Comment by dbmrq** [comment]
Just so you know, https://github.com/Carthage/Carthage/pull/2158 should fix this issue on Carthage's side. That PR isn't included in a release yet, but you can probably go back to using code coverage soon. :)

**Pull request merged**
