### PR TITLE
Rename SWXMLHash class to XMLHash

### PR DESCRIPTION
**Pull request by drmohundro**
Related to #242, see comment specifically at https://github.com/drmohundro/SWXMLHash/issues/242#issuecomment-776060031.

When creating an XCFramework and the .swiftinterface file is created, there are name conflicts. The expectation is that classes within a module wouldn't share the name with the module. Other OSS libraries like this (e.g. Alamofire) have introduced a new name like `AF`.

Of course, the hardest part here is naming... in this case, I just went with `XMLHash` by taking the `SW` prefix off.

I'm still open to other names for the actual type, though.

Things I want to understand prior to merging:

- [ ] How the module name works when using in SPM vs CocoaPods vs Carthage, etc. I want to ensure that the docs are accurate across various dependency distributions.

### CODE REVIEW

**Comment by fgarciaDev** [comment]
In Texas and just getting power and everything back to "normal". Will try this out as soon as I can.

**Comment by drmohundro** [comment]
@fgarciaDev no worries, totally understand, I've got family in Texas. Stay safe and warm!

**Comment by fgarciaDev** [comment]
Tested by specifying this branch in my Swift.Package manifest file. Rebuilt my XCFramework and was able to integrate into new projects without the need to manually edit the generated *.swiftinterface files for this library. Appreciate the work!

**Comment by drmohundro** [comment]
Sounds great! I'd like to at least _think_ about making some possible enhancements as this will be a major version bump. Not at all required, though, but that's my thought process. Sounds like you're good with referring to the branch still, correct? I don't want to cause any blockers for you, though, if I do that.

**Comment by fgarciaDev** [comment]
yes, pointing to your dev branch is fine for now. appreciate it!

**Comment by drmohundro** [comment]
Other references to this or similar issues:

- <https://bugs.swift.org/browse/SR-898>
- <https://developer.apple.com/forums/thread/123253>
- <https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors-inside-swiftinterface/28962>

**Pull request merged**
