### PR TITLE
Update to Swift 2.0 on XCode 7 Beta 6

### PR DESCRIPTION
**Pull request by fluffyemily**
convert string.join(collection) to new collection.joinWithSeparator(string) for Xcode 7 beta 6

### CODE REVIEW

**Comment by drmohundro** [comment]
@fluffyemily this looks great - is there any chance you could also make the same changes for the unit tests as well? I've was using `" ".join` in some places in the tests as well and they'll need to be corrected, too.

See https://github.com/fluffyemily/SWXMLHash/blob/master/Tests/SWXMLHashSpecs.swift#L56 as an example.

**Comment by jpsim** [comment]
FYI: updated this on my personal branch for now, I can make a PR if you'd like

https://github.com/jpsim/SWXMLHash/commit/c382261714ce30688343d7c8b895029bdf353b99

**Comment by fluffyemily** [comment]
@drmohundro updated as requested. Sorry it took so long.

**Comment by drmohundro** [comment]
@fluffyemily I manually merged this in (along with some fixes from @jpsim's branch. Thanks so much both of you! See https://github.com/drmohundro/SWXMLHash/commit/050154bfc56032f04fcca37464693a17f897200a for details.

**Pull request closed without merging**
