### PR TITLE
Fix build error on Swift Package Manager

### PR DESCRIPTION
**Pull request by norio-nomura**
https://travis-ci.org/realm/SwiftLint/jobs/121989579#L499

> SWXMLHash+TypeConversion.swift:341:26: error: use of unresolved identifier 'NSString'

### CODE REVIEW

**Comment by drmohundro** [comment]
I'll get a new point release out to fix this, too, thanks!

**Comment by drmohundro** [comment]
@norio-nomura just pushed `2.3.1` to resolve this - thanks!

**Comment by drmohundro** [comment]
@norio-nomura I noticed your fork already has quite a bit of work to support Swift 3, SPM, etc. Given that Swift 2 and 3 now have breaking changes between them, does it make the most sense to use either compiler directives or to have a separate branch to track Swift 3 support? Do you have any thoughts or recommendations for how I could help avoid issues like this?

I do need to get a CI build going - that's been on my TODO list for a while.

**Comment by norio-nomura** [comment]
Thanks for merging!

> does it make the most sense to use either compiler directives or to have a separate branch to track Swift 3 support?

I guess we need to have a separate branch not because the difference of Standard Library API but because of [SE-0046](https://github.com/apple/swift-evolution/blob/master/proposals/0046-first-label.md) that merged recently.
[SE-0046](https://github.com/apple/swift-evolution/blob/master/proposals/0046-first-label.md) will force us to wrapping our APIs if we'll want to support Swift 2.2 and 3 simultaneously in single branch.

**Pull request merged**
