### PR TITLE
add option for trim whitespace and newline

### PR DESCRIPTION
**Pull request by mqshen**
keep original text in xml like:

       <content type="html">
            &lt;pre&gt;&lt;code&gt;&amp;lt;configuration&amp;gt;
                         &amp;lt;property&amp;gt;
            &amp;lt;name&amp;gt;fs.defaultFS&amp;lt;/name&amp;gt;
            &amp;lt;value&amp;gt;hdfs://master:9000&amp;lt;/value&amp;gt;
                  &amp;lt;/property&amp;gt;
               &amp;lt;property&amp;gt;
       </content>

### CODE REVIEW

**Comment by drmohundro** [comment]
I agree that it would be good to preserve whitespace *within* elements, but my primary concern with a change like this is that, in my experience, `foundCharacters` also matches on whitespace *between* elements (see https://github.com/drmohundro/SWXMLHash/issues/6#issuecomment-58016054).

In other words, give the below XML, whitespace *between* `<content>` and `<stuff>` will also be returned.

```xml
<foo>
  <content>
    <stuff>
      value here
    </stuff>
  </content>
</foo>
```

Do you know if this behavior will result in bugs (or at least unexpected behavior) if `trimwhitespaceAndNewline` is set to `true`?

**Comment by drmohundro** [comment]
I wanted to apologize - I tried this again after #26 came in and it seems that the whitespace behavior I was observing was incorrect. I've merged that PR in, though, which takes the whitespace trimming out completely. If you still feel like it is a good idea to have the trimming as an option (versus simply trimming the result after parse) then feel free to comment back. Thanks!

**Comment by mqshen** [comment]
I add the trimming option because I don't want Influence the legacy code.(I don't know what it work for)
I prefer let user do trim by himself.
Thanks!

**Comment by drmohundro** [comment]
I understand, thanks so much for your input!

**Comment by hansen-m** [comment]
Would providing `trimwhitespaceAndNewline` (default to false) as a configuration option be possible? That would restore the previous behavior of trimming the white space between the elements.

The xml I'm working with is "pretty printed" data, without an encoding declaration, similar to your example. The line breaks (CRLF) and white space between the elements is being returned and causing some havoc.

**Comment by drmohundro** [comment]
@hansen-m apologies on the delayed reply. I still lean towards not having that as a configuration option; however, a more specific example might be helpful because there haven't been a lot of requests for this sort of thing. I would think that, with the deserialization support that is built in for strings, that a call like:

```swift
let trimmedValue: String = xml["foo"]["content"]["stuff"].value().trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)`
```

If there were lots of elements, then a custom deserialization class could handle most if not all of the trimming.

**Comment by hansen-m** [comment]
@drmohundro Thanks for the reply. It's been a while since I looked at this so I'll have to go back and revisit it but what you suggested might be possible. I'm still very new to Swift so I'm sure there are ways I could design it.

The project I'm working on loads the XML content into an NSOutlineView and the way it is loaded the NSOutlineViewDataSource returns the value for the cell and properties of it like children and count. When iterating over the data without having an option like `trimwhitespaceAndNewline` I'm getting tabs and `\r\n` values returned, and trimming would leave just an empty string. 

SWXMLHash actually makes it really easy to incorporate the data into an outline view as long as the data is already sanitized. As a workaround I ended up doing the following before parsing:

```
        let download_data = try! Data(contentsOf: location)
        let replaced_string = String(data: download_data, encoding: .utf8)?
            .replacingOccurrences(of: "\r\n", with: "")
            .replacingOccurrences(of: "  ", with: "")
        
        let parser = SWXMLHash.config {
            config in
            //config.trimwhitespaceAndNewline = true
            }.parse(replaced_string!)
```

Another option would be to fix the source that is generating the XML but that code belongs to another colleague :)

**Comment by drmohundro** [comment]
Gotcha, thanks for the clarification. Well I always welcome feedback and I won't rule out any changes later :) Thanks for your support!

**Pull request closed without merging**
