### PR TITLE
Migrated to Swift 5

### PR DESCRIPTION
**Pull request by K-Be**

### CODE REVIEW

**Comment by drmohundro** [comment]
@K-Be thanks - I'll try to take a look at this soon! I'll have to get the build passing, too, which I think should be a relatively simple fix to the travis CI config.

**Comment by drmohundro** [comment]
@K-Be FYI I just added a small commit on your branch to try to get the travis build working - if we can get a passing build, then I can get this merged.

**Comment by drmohundro** [comment]
`4.9.0` is now released - thanks again @K-Be!

**Comment by YannickBiet** [comment]
Thanks for reporting and having fixed the issue :)
Working great!

**Pull request merged**
