### PR TITLE
Fix tests on Swift Package Manager

### PR DESCRIPTION
**Pull request by norio-nomura**
- Test passes with SPM on macOS
- Test runs on Linux, but failing with 92 failures. :x:
- Run various tests on Travis-CI

### CODE REVIEW

**Comment by norio-nomura** [comment]
Disabled test on Linux since [92 failures](https://travis-ci.org/drmohundro/SWXMLHash/jobs/155911396)

**Comment by norio-nomura** [comment]
As I investigated, the failures on Linux are caused by [SR-2301](https://bugs.swift.org/browse/SR-2301).

**Comment by drmohundro** [comment]
This is great! I've seen the use of `matrix` in the `.travis.yml` but I hadn't had the chance to investigate and implement it yet - awesome! Also, good find on the Swift bug!

**Comment by norio-nomura** [comment]
Thanks! 🙏

**Pull request merged**
